name: Krajina
version: 1.0
main: krajina.MainKrajina
api-version: 1.18

commands:
  +jama:
  +udoli:
  +kopec:
  +kopecek:
  +jezero:
  +jezeroVzduch:
  +reka1:
  +vodniKupole:
  +jeskyne:
  +cesta:
  +cestaSJVZ:
  +trava:
  +kacejStrom:
  +kacejLes:
  +ostrovObdelnik:
  +ostrovKruh:
  +ostrovObdAbs:
  +ostrovKruhAbs:
  +bedWarsOstrov:
  +zarovnejPovrch:
  +vymazKolemHrace: